spring:
  profiles:
    active: "development"
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:mysql://localhost:3306/sda_library?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
  jpa:
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

